-- 코드를 입력하세요
SELECT I.ANIMAL_ID,I.ANIMAL_TYPE,I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (O.SEX_UPON_OUTCOME LIKE '%Spayed%' 
OR O.SEX_UPON_OUTCOME LIKE '%Neutered%')
AND I.SEX_UPON_INTAKE LIKE '%Intact%' #그루핑이 중요함
ORDER BY I.ANIMAL_ID,I.ANIMAL_TYPE,I.NAME

