-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE,E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
#테이블 3개 조인
FROM HR_EMPLOYEES AS E
LEFT JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
LEFT JOIN HR_DEPARTMENT AS D 
ON E.DEPT_ID = D.DEPT_ID
#2022년 사원 평가
WHERE G.YEAR = 2022
GROUP BY G.EMP_NO #JOIN 기준 아닌 컬럼 넣으니까 에러뜸
ORDER BY SCORE DESC
LIMIT 1;