-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, #OVER 함수 / PARTITION BY에는 기준이되는 컬럼을 넣는다
ID
FROM ECOLI_DATA 
ORDER BY YEAR ASC, YEAR_DEV ASC;