-- 코드를 입력하세요
#SELECT *
SELECT PRODUCT_CODE,SUM(P.PRICE*O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
LEFT JOIN OFFLINE_SALE AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;