-- 코드를 작성해주세요

SELECT ROUTE,
CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE, #문자열 붙일 때 CONCAT
CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),"km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) DESC; #누계 거리(NUM) 기준

#ROUND(X,Y) -> X의 Y+1 자리에서 반올림하세요