-- 코드를 입력하세요
-- 서울 위치 식당 ID, 이름, 음식 종류, 즐찾수, 주소, 리뷰 평균 점수(Round @ 3번째 자리)
-- ORDER BY 평균점수 DESC, 즐찾수 DESC
SELECT I.REST_ID, I.REST_NAME , I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울시%'
OR I.ADDRESS LIKE '서울특별시%'
OR I.ADDRESS LIKE '서울%'
GROUP BY I.REST_NAME
ORDER BY SCORE DESC, I.FAVORITES DESC