-- 코드를 입력하세요
#FOOD_TYPE	REST_ID	REST_NAME	FAVORITES
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
#음식 종류 별로 가장 많은 즐겨찾기 받은 식당의 음식 종류와 즐겨찾기 수 튜플로 추출
WHERE (FOOD_TYPE, FAVORITES) IN ( 
    SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;