-- 코드를 작성해주세요
#SubQuery활용이 관건!

#SELECT & 테이블 JOIN
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
# TYPE별로 묶어주기 -> 중첩Sub Query 이용
WHERE (I.FISH_TYPE, LENGTH) IN (
    SELECT FISH_TYPE , MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE )
ORDER BY I.ID ASC;